var nombre_consumidor = [
'Juan',
'Miguel',
'Carlos',
'Josefina',
'Leticia',
'Luis',
'Elizabeth',
'Andrés',
'Luis',
'Andrea',
'José',
'Pedro',
'Jorge',
'José',
'Rosa',
'Armando',
'Gloria',
'Óscar',
'María',
'Isabel',
'José',
'Antonio',
'Verónica',
'Salvador',
'José',
'María',
'María',
'Eduardo',
'Alfredo',
'Santiago',
'Ramón',
'Araceli',
'Lucía',
'María',
'Rafael',
'Gabriela',
'Felipe',
'Carmen',
'Fernando',
'Francisco',
'Juan',
'María',
'Agustín',
'Guadalupe',
'Ricardo',
'Francisca',
'José',
'José',
'Rosa',
'Ruben',
'Diego',
'Yolanda',
'María',
'María',
'Juana',
'Margarita',
'María',
'Ana María',
'María',
'Miguel',
'Alicia',
'Patricia',
'Jaime',
'Gustavo',
'Francisco',
'Arturo',
'Martha',
'Daniel',
'Javier',
'Raúl',
'David',
'Enrique',
'Gerardo',
'María',
'Sergio',
'Víctor',
'María',
'Julio',
'Manuel',
'Juan',
'Roberto',
'Marco',
'Alberto',
'Ángel',
'Mario',
'Teresa',
'María',
'Irma',
'Adriana',
'Silvia',
'Gabriel',
'Guillermo',
'Pablo',
'Jesús',
'Alejandro',
'Martín',
'Alejandra',
'Antonia',
'María',
'Jorge'
];

var apellidos_consumidor = [
'González',
'Morales',
'Castillo',
'Sánchez',
'López',
'González',
'Morales',
'Castillo',
'Sánchez',
'López',
'Muñoz',
'Rodríguez',
'Ramírez',
'Carrasco',
'García',
'Muñoz',
'Rodríguez',
'Ramírez',
'Carrasco',
'García',
'Rojas',
'Martínez',
'Vergara',
'Hernández',
'Vergara',
'Sandoval',
'Torres',
'Castro',
'Vera',
'Pérez',
'Castro',
'Figueroa',
'Molina',
'Contreras',
'Álvarez',
'Fuentes',
'Gómez',
'Vera',
'Espinoza',
'Núñez',
'Martínez',
'Espinoza',
'Campos',
'Soto',
'Reyes',
'Bravo',
'Núñez',
'Herrera',
'Sepúlveda',
'Vásquez',
'Rivera',
'Soto',
'Flores',
'Miranda',
'Silva',
'Hernández',
'Campos',
'Gutiérrez',
'Díaz',
'Gutiérrez',
'Vega',
'Contreras',
'Herrera',
'Orellana',
'Pérez',
'Gómez',
'Díaz',
'Valenzuela',
'Vargas',
'Tapia',
'Fernández',
'Jara',
'Rivera',
'Figueroa',
'Sandoval',
'Torres',
'Vargas',
'Jara',
'Fuentes',
'Araya',
'Flores',
'Cortés',
'Orellana',
'López',
'Miranda',
'Molina',
'Silva',
'Bravo',
'Vega',
'Araya',
'Valenzuela',
'Reyes',
'Álvarez',
'Sepúlveda',
'López',
'Vásquez',
'Rojas',
'Tapia',
'Fernández',
'Cortés'
];

var estados_compra = [
'Aguascalientes',
'Baja California Sur',
'San Luis Potos',
'Nayarit',
'Querétaro',
'Sinaloa',
'Aguascalientes',
'Veracruz',
'Zacatecas',
'Tlaxcala',
'Baja California',
'Campeche',
'CDMX',
'Aguascalientes',
'Quintana Roo',
'Sonora',
'Baja California',
'Yucatán',
'Aguascalientes',
'Michoacán',
'Tabasco',
'Aguascalientes',
'Nuevo León',
'Tlaxcala',
'Sonora',
'Tabasco',
'Chihuahua',
'Guerrero',
'Sonora',
'Tlaxcala',
'Nayarit',
'Tamaulipas',
'San Luis Potos',
'Yucatán',
'Jalisco',
'Tamaulipas',
'Baja California',
'Quintana Roo',
'Querétaro',
'Coahuila de Zaragoza',
'Quintana Roo',
'Aguascalientes',
'Baja California',
'Veracruz',
'Durango',
'Sinaloa',
'Coahuila de Zaragoza',
'Campeche',
'San Luis Potos',
'Veracruz',
'Tabasco',
'Michoacán',
'Nayarit',
'Morelos',
'Zacatecas',
'Chiapas',
'Baja California Sur',
'Morelos',
'Tamaulipas',
'Guanajuato',
'Baja California',
'Morelos',
'Campeche',
'Tamaulipas',
'Tlaxcala',
'Baja California',
'Tamaulipas',
'Quintana Roo',
'Hidalgo',
'Michoacán',
'Morelos',
'Colima',
'Oaxaca',
'Puebla',
'Campeche',
'Michoacán',
'Aguascalientes',
'Sinaloa',
'Colima',
'Oaxaca',
'Puebla',
'Baja California Sur',
'Coahuila de Zaragoza',
'Tabasco',
'San Luis Potos',
'Aguascalientes',
'Querétaro',
'Querétaro',
'Aguascalientes',
'Morelos',
'Baja California',
'Zacatecas',
'Baja California',
'Baja California',
'Coahuila de Zaragoza',
'Estado de México',
'Tabasco',
'Yucatán',
'Zacatecas',
'Baja California Sur'
];

var nombre_libro_compra = [
'Música para difuntos',
'Bestias',
'Vecindad con el abismo',
'De las sombras',
'El extraño caso del Dr. Jekyll y Mr.Hyde',
'Miscelánea cruel',
'Narraciones ocultistas',
'Crónicas de sangre y dolor',
'Sombras sin tiempo',
'Ciencia Divertida',
'Cerebro Traidor Del Ceo',
'Círculo de fuego',
'La leyenda del jinete sin cabeza',
'Hyperia',
'El retrato de Dorian Gray',
'Instrumentos de tortura',
'Cuentos de terror de H.P. Lovecraft',
'Nunca más',
'Frankenstein',
'Novelas de terror de H.P. Lovecraft',
'El fantasma de Canterville',
'Cuentos completos tomo I',
'Cuentos completos tomo II',
'Los fulgores del tigre',
'Álgebra del polvo',
'La Risa',
'La claridad furiosa',
'Música para difuntos',
'Bestias',
'Vecindad con el abismo',
'De las sombras',
'El extraño caso del Dr. Jekyll y Mr.Hyde',
'Naturalia Urbana',
'Miscelánea cruel',
'Narraciones ocultistas',
'Crónicas de sangre y dolor',
'Sombras sin tiempo',
'Filosofía Divertida',
'Círculo de fuego',
'La leyenda del jinete sin cabeza',
'Hyperia',
'El retrato de Dorian Gray',
'Bebe Y Los Libros',
'Instrumentos de tortura',
'Cuentos de terror de H.P. Lovecraft',
'Nunca más',
'Peter Pan',
'Frankenstein',
'Novelas de terror de H.P. Lovecraft',
'Corazón De Las Tinieblas',
'Corazón De Las Tinieblas',
'Recuentos de Moradas',
'Recuento de Moradas',
'Recuento de Moradas',
'El Monje',
'El Monje',
'El Monje',
'El fantasma de Canterville',
'Cuentos completos tomo I',
'Cuentos completos tomo II',
'Los fulgores del tigre',
'Álgebra del polvo',
'La claridad furiosa',
'Burlar Al Diablo',
'Necronomicon',
'Necronomicon',
'Necronomicon',
'Días Terminales',
'Días Terminales',
'Días Terminales',
'Autoestima Para Niñas',
'Autoestima Para Niñas',
'Fulgores Del Tigre',
'Isla Del Doctor Moreau',
'Yo Soy La Puerta',
'Yo Soy La Puerta',
'Yo Soy La Puerta',
'Yo Soy La Puerta',
'Música para difuntos',
'Bestias',
'Vecindad con el abismo',
'Enamorado De La Vida',
'Enamorado De La Vida',
'Enamorado De La Vida',
'Golem, El',
'Momentos Mágicos',
'Yoga Para Corredores',
'Yoga Para Corredores',
'Yoga Para Corredores',
'Cuentos completos tomo I',
'Cuentos completos tomo II',
'Del Bullying Al Asesinato',
'Del Bullying Al Asesinato',
'De las sombras',
'El extraño caso del Dr. Jekyll y Mr.Hyde',
'Miscelánea cruel',
'Claridad Furiosa',
'Claridad Furiosa',
'Claridad Furiosa',
'Claridad Furiosa'
];

var imagen_libro_compra = [
'musicaparadifuntos.jpg',
'bestias.jpg',
'vecindadconelabismo.jpg',
'1560810374delassombras.jpg',
'elextraocasodeldrjekyll1.jpg',
'miscelanea.jpg',
'narracionesocultistas.jpg',
'cronicasdesangreydolor1.jpg',
'sombrassintiempo.jpg',
'cienciadivertida.jpg',
'elcerebrotraidordelceo1.jpg',
'circulodefuego.jpg',
'1565902143eljinetesincabeza.jpg',
'hyperia.jpg',
'doriangray1.jpg',
'instrumentosdetortura.jpg',
'cuentosdeterrordelovecraft2.jpg',
'nuncamas.jpg',
'frank1.jpg',
'novelasdeterrorlovecraft.jpg',
'fantasmadecanterville.jpg',
'cuentoscompletostomoi.jpg',
'cuentoscompletostomoii.jpg',
'losfulgoresdeltigre.jpg',
'1565891470algebradelpolvo.jpg',
'larisa1.jpg',
'1562707259laclaridadfuriosa.jpg',
'musicaparadifuntos.jpg',
'bestias.jpg',
'vecindadconelabismo.jpg',
'1560810374delassombras.jpg',
'elextraocasodeldrjekyll1.jpg',
'naturaliaurbana1.jpg',
'miscelanea.jpg',
'narracionesocultistas.jpg',
'cronicasdesangreydolor1.jpg',
'sombrassintiempo.jpg',
'filosofiacool.jpg',
'circulodefuego.jpg',
'1565902143eljinetesincabeza.jpg',
'hyperia.jpg',
'doriangray1.jpg',
'elbebeyloslibros.jpg',
'instrumentosdetortura.jpg',
'cuentosdeterrordelovecraft2.jpg',
'nuncamas.jpg',
'peterpan.jpg',
'frank1.jpg',
'novelasdeterrorlovecraft.jpg',
'corazondelastinieblas.jpg',
'corazondelastinieblas.jpg',
'recuentodemoradas.jpg',
'recuentodemoradas.jpg',
'recuentodemoradas.jpg',
'1559596081elmonje.jpg',
'1559596081elmonje.jpg',
'1559596081elmonje.jpg',
'fantasmadecanterville.jpg',
'cuentoscompletostomoi.jpg',
'cuentoscompletostomoii.jpg',
'losfulgoresdeltigre.jpg',
'1565891470algebradelpolvo.jpg',
'1562707259laclaridadfuriosa.jpg',
'burlaraldiablo.jpg',
'elnecronomicon.jpg',
'elnecronomicon.jpg',
'elnecronomicon.jpg',
'diasterminales.jpg',
'diasterminales.jpg',
'diasterminales.jpg',
'autoestimaparaninas.jpg',
'autoestimaparaninas.jpg',
'losfulgoresdeltigre.jpg',
'1562707026laisladeldrmoreau.jpg',
'15610519737502275671433.jpg',
'15610519737502275671433.jpg',
'15610519737502275671433.jpg',
'15610519737502275671433.jpg',
'musicaparadifuntos.jpg',
'bestias.jpg',
'vecindadconelabismo.jpg',
'1562707103enamoradodelavida.jpg',
'1562707103enamoradodelavida.jpg',
'1562707103enamoradodelavida.jpg',
'1562695277elgolem.jpg',
'1562696959momentosmagicos.jpg',
'1562697503yogaparacorredores.jpg',
'1562697503yogaparacorredores.jpg',
'1562697503yogaparacorredores.jpg',
'cuentoscompletostomoi.jpg',
'cuentoscompletostomoii.jpg',
'1562697247delbullyingalasesinato.jpg',
'1562697247delbullyingalasesinato.jpg',
'1560810374delassombras.jpg',
'elextraocasodeldrjekyll1.jpg',
'miscelanea.jpg',
'1562707259laclaridadfuriosa.jpg',
'1562707259laclaridadfuriosa.jpg',
'1562707259laclaridadfuriosa.jpg',
'1562707259laclaridadfuriosa.jpg'
];

var horas_compra = [
'hace 1 hora',
'hace 5 horas',
'hace 12 horas',
'hace 7 horas',
'hace 2 horas',
'hace 9 horas',
'hace 8 horas',
'hace 7 horas',
'hace 7 horas',
'hace 12 horas',
'hace 12 horas',
'hace 6 horas',
'hace 1 hora',
'hace 9 horas',
'hace 3 horas',
'hace 9 horas',
'hace 9 horas',
'hace 12 horas',
'hace 12 horas',
'hace 1 hora',
'hace 1 hora',
'hace 10 horas',
'hace 12 horas',
'hace 12 horas',
'hace 1 hora',
'hace 7 horas',
'hace 9 horas',
'hace 8 horas',
'hace 10 horas',
'hace 12 horas',
'hace 10 horas',
'hace 9 horas',
'hace 9 horas',
'hace 9 horas',
'hace 10 horas',
'hace 11 horas',
'hace 8 horas',
'hace 7 horas',
'hace 12 horas',
'hace 12 horas',
'hace 7 horas',
'hace 12 horas',
'hace 1 hora',
'hace 3 horas',
'hace 7 horas',
'hace 9 horas',
'hace 11 horas',
'hace 7 horas',
'hace 12 horas',
'hace 1 hora',
'hace 7 horas',
'hace 1 hora',
'hace 9 horas',
'hace 7 horas',
'hace 9 horas',
'hace 9 horas',
'hace 6 horas',
'hace 9 horas',
'hace 7 horas',
'hace 12 horas',
'hace 5 horas',
'hace 12 horas',
'hace 10 horas',
'hace 12 horas',
'hace 2 horas',
'hace 12 horas',
'hace 11 horas',
'hace 1 hora',
'hace 9 horas',
'hace 12 horas',
'hace 1 hora',
'hace 1 hora',
'hace 1 hora',
'hace 7 horas',
'hace 7 horas',
'hace 1 hora',
'hace 11 horas',
'hace 12 horas',
'hace 7 horas',
'hace 10 horas',
'hace 11 horas',
'hace 1 hora',
'hace 7 horas',
'hace 10 horas',
'hace 9 horas',
'hace 4 horas',
'hace 1 hora',
'hace 12 horas',
'hace 12 horas',
'hace 7 horas',
'hace 1 hora',
'hace 9 horas',
'hace 12 horas',
'hace 4 horas',
'hace 7 horas',
'hace 11 horas',
'hace 10 horas',
'hace 12 horas',
'hace 1 hora',
'hace 9 horas'
];


var id_libro_compra = [
'347',
'324',
'1495',
'1565',
'944',
'345',
'1218',
'825',
'361',
'1515',
'1573',
'328',
'1637',
'341',
'377',
'1511',
'836',
'1231',
'229',
'1224',
'227',
'209',
'210',
'1608',
'1633',
'1574',
'1626',
'347',
'324',
'1495',
'1565',
'944',
'1575',
'345',
'1218',
'825',
'361',
'1576',
'328',
'1637',
'341',
'377',
'1580',
'1511',
'836',
'1231',
'1581',
'229',
'1224',
'1584',
'1584',
'1590',
'1590',
'1590',
'1594',
'1594',
'1594',
'227',
'209',
'210',
'1608',
'1633',
'1626',
'1604',
'1605',
'1605',
'1605',
'1606',
'1606',
'1606',
'1607',
'1607',
'1608',
'1610',
'1611',
'1611',
'1611',
'1611',
'347',
'324',
'1495',
'1612',
'1612',
'1612',
'1613',
'1614',
'1615',
'1615',
'1615',
'209',
'210',
'1625',
'1625',
'1565',
'944',
'345',
'1626',
'1626',
'1626',
'1626'
];